theme: jekyll-theme-minimal
title: Children's Services Data Hub
description: This hub provides you with a range of open source code to clean, edit and analyse statutory children's services data (Annex A, Cin Census, 903). Anyone is welcome to add their own work to this hub! Simply contact us at tom.rintoul@socialfinance.org.uk.
